[package]
name = "wgpu-quick"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.12.0"
bytemuck = "*"
winit = "0.26.1"
anyhow = "1.0.52"
image = "0.23.14"

[dev-dependencies]
winit = "0.26.1"
pollster = "0.2.5"